CREATE TABLE DOCS (LINE STRING);

LOAD DATA INPATH '/user/maria_dev/countries_list.txt' OVERWRITE INTO TABLE DOCS;

CREATE TABLE WORD_COUNTS AS 
SELECT WORD,COUNT(1) AS COUNT FROM
(SELECT EXPLODE(SPLIT(LINE,'\s')) AS WORD FROM DOCS) w
GROUP BY WORD
ORDER BY WORD;